apiVersion: v1
kind: Secret
metadata:
  name: pingone-admin
stringData:
  environmentId: REPLACE_WITH_ENV_ID
  clientId: REPLACE_WITH_WORKER_CLIENT_ID
---
apiVersion: v1
kind: Secret
metadata:
  name: openai-api
stringData:
  apiKey: REPLACE_WITH_OPENAI_API_KEY
